# version: '3'

services:
  mongodb:
    image: mongo:7.0.14
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      bindIp: 127.0.0.1
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ${PWD:-.}/volumes:/data/db
      - ${PWD:-.}/mongo.config.yaml:/etc/mongod.conf
      - /etc/localtime:/etc/localtime:ro
    command: mongod --config /etc/mongod.conf
    # networks:
    #   - mongodb

      
